"use strict";
// --- ฟังก์ชันหลักสำหรับเปิดหน้าและคำนวณ ---
function showDailyHighlightPage() {
    // 1. ตั้งค่าวันที่ใน Input ให้เป็นวันนี้ (ป้องกันค่าว่าง)
    const today = new Date().toISOString().split('T')[0];
    const picker = document.getElementById('highlightDatePicker');
    if (picker) picker.value = today;
    
    // 2. เปลี่ยนหน้าไปที่หน้าแผนที่ฤกษ์
    navigateTo('dailyHighlightPage');
    
    // 3. สั่งวาดข้อมูลลงตารางทันที
    generateDailyMap();
}

function generateDailyMap() {
    const dateVal = document.getElementById('highlightDatePicker').value;
    if (!dateVal) return;

    const targetDate = new Date(dateVal);
    const dayOfWeek = targetDate.getDay(); // 0 = อาทิตย์, 1 = จันทร์...
    
    // แสดงวันที่ภาษาไทยบนหัวข้อ
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    document.getElementById('mapDateTitle').innerText = targetDate.toLocaleDateString('th-TH', options);

    const dayContainer = document.getElementById('dayYarmList');
    const nightContainer = document.getElementById('nightYarmList');
    
    dayContainer.innerHTML = '';
    nightContainer.innerHTML = '';

    const timeLabels = [
        "06:00 - 07:30", "07:30 - 09:00", "09:00 - 10:30", "10:30 - 12:00",
        "12:00 - 13:30", "13:30 - 15:00", "15:00 - 16:30", "16:30 - 18:00", // กลางวัน
        "18:00 - 19:30", "19:30 - 21:00", "21:00 - 22:30", "22:30 - 00:00",
        "00:00 - 01:30", "01:30 - 03:00", "03:00 - 04:30", "04:30 - 06:00"  // กลางคืน
    ];

    // วาดกลางวัน 8 ยาม
    for (let i = 0; i < 8; i++) {
        const starId = YARM_CHART.day[dayOfWeek][i];
        dayContainer.appendChild(renderYarmRow(timeLabels[i], starId));
    }

    // วาดกลางคืน 8 ยาม
    for (let i = 0; i < 8; i++) {
        const starId = YARM_CHART.night[dayOfWeek][i];
        nightContainer.appendChild(renderYarmRow(timeLabels[i + 8], starId));
    }
}

// --- ฟังก์ชันสำหรับสร้างแถวข้อมูล (เวอร์ชันปรับปรุงคะแนนดาว) ---
function renderYarmRow(timeRange, starId) {
    const info = YARM_INFO[starId];
    const color = getStarColor(starId);
    
    // ปรับ Logic การให้คะแนนดาวตามความหมายใน yarmPage.js
    let count = 4; // ค่าเริ่มต้น
    
    // กลุ่มมงคลสูง (อาทิตย์, จันทร์, พฤหัสบดี, ศุกร์)
    if ([0, 1, 5, 6].includes(starId)) {
        count = 5;
    } 
    // กลุ่มที่ต้องระวังเป็นพิเศษ (เสาร์, ราหู)
    else if ([4, 7].includes(starId)) {
        count = 3;
    }
    // กลุ่มยามพุธ (3) และ อังคาร (2) จะได้ 4 ดาวตามค่าเริ่มต้น

    let stars = "";
    for(let i=0; i<count; i++) stars += "⭐";

    const div = document.createElement('div');
    div.className = "yarm-row-mobile animate__animated animate__fadeIn";
    div.style.borderLeftColor = color;
    
    div.innerHTML = `
        <div style="flex: 1.2;">
            <div style="color: #aaa; font-size: 14px; margin-bottom: 2px;">
                <i class="far fa-clock"></i> ${timeRange}
            </div>
            <div style="color: ${color}; font-size: 18px; font-weight: bold;">
                ${info.name}
            </div>
            <div style="font-size: 10px;">${stars}</div>
        </div>
        <div style="flex: 2; text-align: right;">
            <div style="color: #fff; font-size: 15px; font-weight: 500; line-height: 1.2;">
                ${info.good}
            </div>
        </div>
    `;
    return div;
}



// --- ฟังก์ชันเซฟรูปภาพ (เพิ่มพารามิเตอร์ event เพื่อความถูกต้อง) ---
async function downloadDailyMap(element) {
    const area = document.getElementById('dailyMapCapture');
    if (!area) return;

    let btn = element instanceof HTMLElement ? element : document.querySelector('.download-btn');
    const originalText = btn ? btn.innerHTML : "";

    if (btn) {
        btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> กำลังดีไซน์ภาพสำหรับ Facebook...';
        btn.disabled = true;
    }

    // 1. สร้าง Footer Element ชั่วคราว
    const footer = document.createElement('div');
    footer.id = 'temp-footer';
    footer.innerHTML = `
        <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 20px; padding-top: 15px; border-top: 1px solid rgba(212,175,55,0.3); color: #d4af37;">
            <div style="font-size: 14px;">🔮 <strong>สยามโหรามงคล</strong> | เว็บดูดวงและฤกษ์มงคล</div>
            <div style="font-size: 12px; opacity: 0.8;">Generated by นายพิรุฬห์ บุญเพ็ชร์</div>
        </div>
    `;

    try {
        // 2. ปรับแต่งพื้นที่ก่อนแคป
        const originalStyle = area.style.cssText;
        area.style.width = "500px"; 
        area.style.padding = "30px"; // เพิ่มพื้นที่ขอบให้ดูแพง
        area.style.background = "#1a1a1a";
        
        // ใส่ Footer เข้าไปใน Area ที่จะแคป
        area.appendChild(footer);

        const options = {
            backgroundColor: '#1a1a1a',
            scale: 2.2, 
            useCORS: true,
            allowTaint: false,
            scrollY: -window.scrollY,
            windowWidth: 500
        };

        const canvas = await html2canvas(area, options);
        
        // 3. คืนค่าเดิมทันทีหลังจากแคปเสร็จ
        area.removeChild(footer);
        area.style.cssText = originalStyle;

        canvas.toBlob((blob) => {
            if (!blob) return;
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            const dateTitle = document.getElementById('mapDateTitle')?.innerText || 'Daily';
            
            link.download = `ฤกษ์มงคล_Facebook_${dateTitle.replace(/\s+/g, '_')}.png`;
            link.href = url;
            link.click();
            
            setTimeout(() => URL.revokeObjectURL(url), 100);
        }, 'image/png', 0.9);

    } catch (e) {
        console.error("Capture Error:", e);
        alert("ขออภัย! ระบบสร้างภาพขัดข้อง: " + e.message);
    } finally {
        if (btn) {
            btn.innerHTML = originalText;
            btn.disabled = false;
        }
    }
}